# Generated by Django 4.2.6 on 2023-10-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT'), ('Mobiles Ph', 'Mobiles Ph')], max_length=100)),
                ('added_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
